#!/usr/bin/env bash

set -e 

./replicated-splinterdb/start_servers.sh 250

docker run --rm \
    --network splinterdb-network \
    neilk3/ycsb-replicated-splinterdb \
        -load -t -s \
        -db replicated-splinterdb \
        -threads 10 \
        -P 700k \
        -p replicated_splinterdb.host=replicated-splinterdb-node-1

# ./replicated-splinterdb/client.sh 1 -e dumpcache

# echo -n "Waiting for cache dump file to be created "
# while ! stat caches/node-3/stats 2> /dev/null ; do 
#     echo -n "."
#     sleep 1
# done
# echo "done"

# ./analyze.py